[config]
schemaVersion = "1.0.0"

[package]
namespace = "Binbin"
name = "Speed_Up"
versionNumber = "1.0.0"
description = "A mod that DescriptionToReplace"
websiteUrl = "https://github.com/binbinmods/SpeedUp"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_AcrossTheObelisk = "5.4.23"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./SpeedUp"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "across-the-obelisk", ]
[publish.categories]
across-the-obelisk = [ "mods", ]


